### ISSUE TITLE
Error installing into VS2013 -The extension requires a version of the .NET Framework that is not installed

### ISSUE THREAD

**Issue by damianh** [anaisbetts/SaveAllTheTime#39]
Fresh build of a windows box, reinstalling-all-the-things and got this:

![image](https://cloud.githubusercontent.com/assets/57436/7445445/0400dbe8-f1b4-11e4-9f52-b9e85a29bf3d.png)
- VS2013 Update 4.
- VS2015 RC (which installed .net 4.6 RC which I suspect is related)

I don't know a whole lot about vsix, but my suspicion is [this line](https://github.com/paulcbetts/SaveAllTheTime/blob/master/SaveAllTheTime/source.extension.vsixmanifest#L17) is related.

In contrast, [this extension](https://github.com/nagits/BuildVision/blob/master/Source/source.extension.vsixmanifest) installs without a problem. This may only prove that extensions can be installed oc...

**Comment by JeffLeBert** [comment]
I believe @damianh is correct about the line. This is how I have my extensions set up:
    <Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" d:Source="Manual" Version="[4.5,)" />

Note the version says you must have at least .Net 4.5 or any version above that.

**Comment by paulcbetts** [comment]
I don't really use Visual Studio anymore and trying to upgrade this VSIX to be buildable has proven to be a nightmare. Sorry!

**Comment by JeffLeBert** [comment]
For those that still want to use this extension, you can actually edit the *.vsix file yourself! It's just a *.zip file with a different extension. I haven't looked at this specific extension but there should be a file named extension.vsixmanifest. Edit that and change the version to Version="[4.5,)" in the line that @damianh specified. You can also change what versions of Visual Studio the extension will install into.
